### ISSUE TITLE
Cannot launch

### ISSUE THREAD

**Issue by muelleel** [rexjohannes/rex-crack#3]
Hey,
I'm trying to get multiple (cracked) clients running to test my Server Plugins, since i do not own multiple real Minecraft accounts.

Complete log: https://pastebin.com/19igsGpk

Trace:
```
Traceback (most recent call last):
  File "main.py", line 50, in <module>
    args = pml.startProfile(inputVersion, 
  File "/home/elias/Downloads/rex-crack/pmlauncher/pml.py", line 41, in startProfile
    downloadProfile(profile)
  File "/home/elias/Downloads/rex-crack/pmlauncher/pml.py", line 36, in downloadProfile
    downloader.downloadAll(downloadAssets)
  File "/home/elias/Downloads/rex-crack/pmlauncher/mdownloader.py", line 65, in downloadAll
    self.downloadResources()
  File "/home/elias/Downloads/rex-crack/pmlauncher/mdownloader.py", line 89, in downloadResources
    content = f.read()
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

The Launcher simply crashes after the librarys got downloaded.
Any idea?
Thanks

**Comment by rexjohannes** [comment]
Hey,

are you on Linux or Windows? How did you installed the Launcher?

Kind Regards,
rexjohannes

**Comment by muelleel** [comment]
Sorry for not including this Information in the first place.

I've installed it by executing the "sh"-script from the latest release. After that I ran the `run.sh`!

my machine is running Linux Kernel 5.15.0-41-generic x86_64 -> Ubuntu

`python --version -> Python 2.7.18`
`python3 --version -> Python 3.8.10`

**Comment by rexjohannes** [comment]
Okay, i did some research and found out that this project is now broke since mojang changed something. As this project is discontinued and 3 years since last real commit i wont fix it. You could take a look at the Awesome Tlauncher at https://tlauncher.org/en/

I will close this issue and archive this repo in a few hours.

Kind Regards,
rexjohannes
